CREATE DATABASE IF NOT EXISTS alerta_sono;

USE alerta_sono;

CREATE TABLE usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL
);


SHOW VARIABLES LIKE 'port';